# Generated by Django 5.2 on 2025-04-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': '博客类别管理',
                'verbose_name_plural': '博客类别管理',
            },
        ),
    ]
